name: xp0

on:
  workflow_dispatch:
  schedule:
     - cron: '51 21-23,0-4 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        VIDEOHEADER: ${{ secrets.VIDEOHEADER }}
        VIDEOBODY: ${{ secrets.VIDEOBODY }}        
        GOLDBODY: ${{ secrets.GOLDBODY }}
        TZ: Asia/shanghai
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/SamWu129/Js202012.git ~/Js202012
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/Js202012
          npm install
      - name: '运行 【xp0】'
        if: env.VIDEOHEADER
        run: |
          cd ~/Js202012
          node xp/xp0.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
